comet_logger:
  initialize: true
  api_key: null
  project_name: null
  workspace: null
  name: null

early_stopping:
  initialize: true
  patience: 3
  min_delta: 0.001

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  num_workers: 8
  optimizer: TODO
  loss: TODO

model:
  use_pretrained: true
  path_to_weights: '/storage/homefs/tf24s166/code/cifar10/outputs/2024-11-18/15-44-20/best_model.pth'

data:
  data_path: "/storage/homefs/tf24s166/code/cifar10/data"
  label_path: TODO
  target_column: target
  features: TODO

